### ISSUE TITLE
Bypass-  If there is any error and the user is activated for 2wayauthenticate then it won't show the issue .

### ISSUE THREAD

**Issue by rbslvivek** [ssv445/Joomla-Two-Factor-Authentication#32]
It redirect it to 2fa after login and then without showing any error just works fine.
In case if i try to login with different user then they will get the issues,
![selection_772](https://f.cloud.github.com/assets/1694761/1371189/0355e320-3a34-11e3-9e3b-8b65e5cfa2a7.png)

**Comment by mManishTrivedi** [comment]
Yeah, It might be conflict with other system. When they are working on after login's trigger.
