### ISSUE TITLE
Due to change in name, multiple instance get created 

### ISSUE THREAD

**Issue by rbslvivek** [ssv445/Joomla-Two-Factor-Authentication#43]
![selection_890](https://f.cloud.github.com/assets/1694761/1619715/9aa43d1e-5661-11e3-89e0-5594d55ee875.png)
![selection_891](https://f.cloud.github.com/assets/1694761/1619737/fda64d94-5661-11e3-843a-53a2a7f50248.png)
![selection_892](https://f.cloud.github.com/assets/1694761/1619738/fda74e4c-5661-11e3-823d-c0952e04a65a.png)

**Comment by mManishTrivedi** [comment]
You are tracking our TFA with Joomla TFA system. :dancers:
