### ISSUE TITLE
Login not possible to Joomla 3.6.0 using TFA

### ISSUE THREAD

**Issue by VolleyTom** [ssv445/Joomla-Two-Factor-Authentication#63]
I ugraded Joomla from 3.5.1 to 3.6.0 and after the upgrade i wasn't able to log in, because there is a loop after user and passwort whith the TFA-Formular.
![tfa](https://cloud.githubusercontent.com/assets/16403064/16873015/cf975f76-4a90-11e6-9648-cd26a9a3e1c0.JPG)
If i enter a wrong number, i got the error message, with the right code, there is no error message, only again the formular.

br
Tom

**Comment by VolleyTom** [comment]
Additional Info, I'm using TFA Version 2.2.

**Comment by Plinzen** [comment]
I got the same issue. Is their any way to disable the plugin?

**Comment by Plinzen** [comment]
Ok, I got a workaround. With phpmyadmin open the table ending with "_extensions" and search for the entry "Two Factor Authentication", "tfa" and disable the plugin by setting enabled to 0.

**Comment by VolleyTom** [comment]
I disabled the Plugin via GUI => Plugins => Disable!

**Comment by VolleyTom** [comment]
I made some researches and found out, that the user with the changed "user"-Infos is not set.
        $session = JFactory::getSession();
        $user = $session->get('user') ;
        $user->tfa = $this->_is_varified;
        $session->set('user',$user);            <<< NOT SET
After the redirect, and the user-GET, the "tfa" is not set:
        $user = JFactory::getSession()->get('user') ;

It seems that the "Session-User" is overwritten by the default-settings, without "tfa".

Has someone an idee, how to fix this issue?

br

**Comment by Plinzen** [comment]
Hmm, I simply use the official joomla plugin now. Joomla 3.6 has built-in Google Authenticator support.

**Comment by VolleyTom** [comment]
Thanks for this info, i activated the plugin!
