### ISSUE TITLE
Locked out

### ISSUE THREAD

**Issue by geoff3b** [ssv445/Joomla-Two-Factor-Authentication#64]
I have set Two factor up with the basic code always on, worked fine for about 6 months.
Now it fails to log me in, also I click backup-code and get a 'System Email Fail to' my nominated email which I have checked and works fine.
How do I fix this lock-out?
![screenshot](https://cloud.githubusercontent.com/assets/20885539/17708008/50d64fc6-6426-11e6-8f6c-4cb0d34466a7.jpg)

**Comment by supermikael** [comment]
I have the same problem. Get teh same email fail message
After updating to latest version of joomla, I can not login anymore with authenticator. even with a backup code not possible.

**Comment by rbsl-dinesh** [comment]
Hello,

Please download the latest version 2.3 of two factor authentication plugin from our [readybytes](http://www.readybytes.net/labs.html) site. There were some changes in Joomla latest version because of which it was not working properly.

**Comment by geoff3b** [comment]
I managed to fix by searching cPanel file manager, and deleting all related to Two factor and 'tfa'.
Dot think I will use again.

**Comment by supermikael** [comment]
Geoff3b,

Cn you please tell me which files you deleted ?
I need to do the same

_Best regards_
_Michael__---------------------------_

2016-08-28 7:54 GMT+02:00 geoff3b notifications@github.com:
